version: '3.8'

services:
  mysql:
    network_mode: 'host'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  php:
    network_mode: 'host'
    build:
      context: .
      dockerfile: ./chusei/Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/vendor
    ports:
      - 8000:8000
  node:
    network_mode: 'host'
    build:
      context: .
      dockerfile: ./alcazan-forest-front/Dockerfile.front.dev
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: volume
        target: /app/node_modules
      - type: bind
        target: /app
        source: ./alcazan-forest-front


volumes:
  database:
  tls: